apiVersion: v1
kind: ConfigMap
metadata:
  name: solr-config
  labels:
    app.kubernetes.io/name: solr
    app.kubernetes.io/instance: solr
data:
  solr.xml: |
    <!-- place your solr.xml here if needed -->

