apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: StatefulSet
      name: solr
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3

      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"

      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe
        value:
          httpGet:
            path: /solr/admin/info/system
            port: 8983
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 6

      - op: remove
        path: /spec/template/spec/containers/0/livenessProbe

      - op: remove
        path: /spec/template/spec/containers/0/startupProbe

patchesStrategicMerge:
  - patch-zk-host.yaml

