apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solr-minikube-ha
spec:
  project: default
  source:
    repoURL: https://github.com/Gerolsteiner99/minikube-solr-config.git
    path: apps/solr/overlays/minikube-ha
  destination:
    server: https://kubernetes.default.svc
    namespace: solr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
